### ISSUE TITLE
Alpine: unable to add apk mosquitto-1.4.10-r2

### ISSUE THREAD

**Issue by abhayghatpande** [dnavarrom/aws_mosquitto_broker#1]
Hi Diego,

First of all a great thank you for creating this MQTT broker. Really appreciate it.  A small change is needed.

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  mosquitto-1.4.12-r0:
    breaks: world[mosquitto=1.4.10-r2]
The command '/bin/sh -c apk --no-cache add mosquitto=1.4.10-r2 &&     mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log &&     chmod -R 777 /mosquitto &&     chown -R mosquitto:mosquitto /mosquitto' returned a non-zero code: 1
```

The mosquitto package has to be update to mosquitto-1-4.12-r0 for it to build. Also I used Alpine 3.6 instead of 3.5.

Should I send you a PR for the Dockerfile? The updates are really minor ...

**Comment by dnavarrom** [comment]
Thank you Abhay, I've updated mosquitto and alpine versions.
